Jonnitto:
  Maps:
    mapLibrary: 'MapLibre'
    mapService: 'Stadiamaps'
    pinColor: 'oklch(var(--color-accent-l) var(--color-accent-c) var(--color-accent-h))'
    Stadiamaps:
      style:
        light: osm_bright
        dark: alidade_smooth_dark
        basedOn: class
